### ISSUE TITLE
Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given

### ISSUE THREAD

**Issue by grandeljay** [pwkip/contact-form-7-conditional-fields#89]
Just browsing through my logs and found this.

```log
PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/wordpress/wp-content/plugins/cf7-conditional-fields/Wpcf7cfMailParser.php:33
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/cf7-conditional-fields/Wpcf7cfMailParser.php(33): in_array('group-rueckmeld...', NULL)
#1 [internal function]: Wpcf7cfMailParser->hide_hidden_mail_fields_regex_callback(Array)
#2 /var/www/wordpress/wp-content/plugins/cf7-conditional-fields/Wpcf7cfMailParser.php(21): preg_replace_callback('@\\[[\\s]*([a-zA-...', Array, '<h1>Page report...')
#3 /var/www/wordpress/wp-content/plugins/cf7-conditional-fields/cf7cf.php(261): Wpcf7cfMailParser->getParsedMail()
#4 /var/www/wordpress/wp-includes/class-wp-hook.php(303): CF7CF->hide_hidden_mail_fields(Object(WPCF7_ContactForm), false, Object(WPCF7_Submission))
#5 /var/www/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#6 /var/www/wordpress/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#7 /var/www/wordpress/wp-content/plugins/contact-form-7/includes/submission.php(617): do_action_ref_array('wpcf7_before_se...', Array)
#8 /var/www/wordpress/wp-content/plugins/contact-form-7/includes/submission.php(86): WPCF7_Submission->before_send_mail()
#9 /var/www/wordpress/wp-content/plugins/contact-form-7/includes/submission.php(27): WPCF7_Submission->proceed()
#10 /var/www/wordpress/wp-content/plugins/contact-form-7/includes/contact-form.php(1042): WPCF7_Submission::get_instance(Object(WPCF7_ContactForm), Array)
#11 /var/www/wordpress/wp-content/plugins/contact-form-7/includes/controller.php(25): WPCF7_ContactForm->submit()
#12 /var/www/wordpress/wp-includes/class-wp-hook.php(301): wpcf7_control_init()
#13 /var/www/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#14 /var/www/wordpress/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#15 /var/www/wordpress/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#16 /var/www/wordpress/wp-includes/class-wp.php(750): WP->parse_request('')
#17 /var/www/wordpress/wp-includes/functions.php(1291): WP->main('')
#18 /var/www/wordpress/wp-blog-header.php(16): wp()
#19 /var/www/wordpress/index.php(17): require('/var/www/custom...')
#20 {main}
  thrown in /var/www/wordpress/wp-content/plugins/cf7-conditional-fields/Wpcf7cfMailParser.php on line 33
```

**Comment by pwkip** [comment]
Just got a new report about this issue. Haven't been able to reproduce it yet. Any clues are welcome

**Comment by benjaminpick** [comment]
This is a PHP error that is thrown only in PHP 8 ... so probably the problem (why haystack becomes NULL sometimes) has existed before but has gone unnoticed. IMO you  should add an extra check with `if (!is_array($...)) { /* treating this case in some way */ }`

**Comment by pwkip** [comment]
thanks @benjaminpick, this seems to be the reason indeed. However, the second parameter (`$hidden_groups`) should always be an array. This variable comes from a hidden field that is populated with some javascript (the value is a JSON array), and then posted via an Ajax call and decoded during form submission. The only reasons I can think of is that this error occurs when there is either a javascript error or when the JS script isn't loaded at all.

@grandeljay I don't believe this error needs a fix, because it is most likely caused by a javascript error earlier on. I'm willing to reopen this if someone can create a sample form where this error is triggered. (Feel free to use the form tester for this https://conditional-fields-cf7.bdwm.be/form-tester/)
